MAIN_COLOUR = "gray"
MAIN_FRAME_COLOR = "gray"
MAIN_COLOUR_LABEL_BG = "gray"
MAIN_COLOUR_LABEL_TEXT = "white"
CANVAS_COLOUR = "white"
LINE_COLOUR = "blue"

COLUMNS = 22

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 700

DATA_SITUATION = 1/5
BORDERS_SPACE = 5

DATA_FRAME_WIGHT = WINDOW_WIDTH * DATA_SITUATION - BORDERS_SPACE
DATA_FRAME_HEIGHT = WINDOW_HEIGHT - 2 * BORDERS_SPACE

CANVAS_SITUATION = 1 - DATA_SITUATION
CANVAS_WIDTH = WINDOW_WIDTH * CANVAS_SITUATION - 2 * BORDERS_SPACE
CANVAS_HEIGHT = WINDOW_HEIGHT - 2 * BORDERS_SPACE